"""add_budget_past_spending

Revision ID: f01d5319e7b1
Revises: b6c3f9b2e4d1
Create Date: 2026-05-30 22:17:56.074981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f01d5319e7b1'
down_revision: Union[str, Sequence[str], None] = 'b6c3f9b2e4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('past_spending', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('budgets', sa.Column('reduction_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'reduction_percent')
    op.drop_column('budgets', 'past_spending')
    # ### end Alembic commands ###
